FROM node:18-alpine

WORKDIR /app

# 安装开发依赖
RUN apk add --no-cache python3 make g++ postgresql-client

# 设置npm镜像
RUN npm config set registry https://registry.npmmirror.com

COPY package*.json ./
RUN npm install

COPY . .

# 生成Prisma客户端
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"] 